### ISSUE TITLE
TODO: Features to implement

### ISSUE THREAD

**Issue by utf-4096** [utf-4096/butterspades#2]
**TODO**
- [x] Fix crash when connecting to a 0.76 server from server list
- [x] Add exit button in main menu
- [x] Make newest messages appear from the bottom when chat is opened (toggleable in config)
- [x] Let settings be changed in-game
- [x] Allow Y-Clamp in spectator
- [ ] Add smooth camera in spectator
- [x] Add configurable fly speed
- [x] Add toggleable spectator xray
- [x] Add toggleable name and health display in spec

**Comment by X-DE1** [comment]
My fps drops to 17 when I open the chat, the kamikaze bug is not fixed I say this because in betterspades it is already fixed and when activating the show fps option sometimes you cannot see it because the chat hides the fps I think it should be in another position ;)
https://github.com/xtreme8000/BetterSpades/commit/ec459247d5629c23e61dd3039bb35eb593efeae3
It would be great if they fixed the Go through blocks bug making you unable to type while crouched
https://github.com/xtreme8000/BetterSpades/issues/154

**Comment by utf-4096** [comment]
Thanks for the report. I've created separate issues for these bugs.
